kind: pipeline
name: cicd
type: docker

clone:
  disable: true
steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: clone
    image: alpine/git
    pull: if-not-exists
    environment:
      http_proxy: 
        from_secret: PROXY
      https_proxy:
        from_secret: PROXY
    commands:
    - git clone https://github.com/dataelement/bisheng-unstructured.git .
    - git checkout $DRONE_COMMIT

  - name: build_docker
    pull: if-not-exists
    image: plugins/docker
    privileged: true
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: apt-cache
        path: /var/cache/apt/archives # 将应用打包好的Jar和执行脚本挂载出来
      - name: socket
        path: /var/run/docker.sock
    settings:
      registry: http://192.168.106.8:6082
      insecure: true
      purge: true
      repo: 192.168.106.8:6082/dataelement/bisheng-unstructured
      tags: [ release ]
      context: ./
      dockerfile: ./docker/Dockerfile        
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASSWORD
volumes:
- name: bisheng-cache
  host:
    path: /opt/drone/data/bisheng/
- name: apt-cache
  host:
    path: /opt/drone/data/bisheng/apt/
- name: socket
  host:
    path: /var/run/docker.sock