exclude: ^scripts|docs|docker|requirements|README.md
repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    additional_dependencies: [toml]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    args: ["--line-length=100"]
    language_version: python3
    types_or: [python, cython]

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=100, --select=C,E,F,W,B,B950, --extend-ignore = E203,E501]
    types_or: [python, cython]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    additional_dependencies: [tomli]
    args: ["--toml", "pyproject.toml"]
    exclude: (?x)^(.*stemmer.*|.*stop_words.*|^CHANGELOG.md$)

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
    exclude: ^deploy(\/[^\/]+)*\/templates\/.*$
  # - id: check-shebang-scripts-are-executable
  - id: end-of-file-fixer
    types_or: [c, c++, cuda, proto, java, python]
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

# - repo: local
#   hooks:
#     - id: clang-format
#       name: clang-format
#       description: Format files with ClangFormat
#       entry: clang-format -i
#       language: system
#       files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
